language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests
- coverage run --source=objectpath setup.py test
deploy:
  provider: pypi
  user: chris.lapa
  password:
    secure: Zc5fFjRFIQea1zVQ6xgF5SN/lYK46ptZxeWJnV3lvjLf7suDfCIgQzxWIMxTNBMzSZq51R9xdUreVncpUle1YxjhJfHuqvk3wdCm6AcFjdPuk2uK2jC8sGAGFAMDxsPYC82DIMcima2FqWfTpr1xx47WYFsjKBB4RyV5QkWzBTYVOzh0KM3U6dv6P3GHl7OGIMfIB3gX8q7s/+IG5ES/G/2Ws0m+6Z8puujU6Rjrlq1c0PHUNr576/qA3kO9mU3w0+mHj3zdpwXApDW/YRSGix0WHzVQfaoiBA1PnEoQHtAvgkZHRJ8NkE0vLXnEzQLzL27BJHSky59fYaHi+xmBaLv/1GEjC1cQpB/bpzI9XW+5QycWTkOhMTYuRJnaPQVpxDp26/9PVJRnmcCmC68SFEf2BccHvi4PmWW9EL2/YCggbvTzJeiOMW02YnENk03+SZHrkBrDhnjaXq6ztt+8XkH+YMmVobCU7BXBlk6E0wbXjdfFSx4HtITJqQY3XbfMVU7ZqI0XgSGv82ITMlFF5LNIf0vewYRtS6U2J9TdzJOVaGUN6K6C+kSVuoaX8dnidnbuDc2JBeFH+TLTCV6GU3y2Z3ML/30fZYbRF4Ug2vcDOBfwAMRDIW1W9Z06twRWLNg8vgFAR41uBMG04oe+lidtBOfX+0Wc0Hz+au+8RXc=
  on:
    tags: true
    repo: objectpath/ObjectPath
    python: '3.7'
  distributions: sdist bdist_wheel
after_success:
- coveralls
